apiVersion: v1
kind: Service
metadata:
  labels:
    app: result
  name: result
spec:
  type: {{ .Values.result.service.type }}
  ports:
  - name: {{ .Values.result.service.name }}
    port: 8081
    targetPort: 80
    nodePort: 31001
  selector:
    app: result
