apiVersion: v1
kind: Service
metadata:
  labels:
    app: vote
  name: vote
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
  - name: {{ .Values.frontend.service.name }}
    port: 8080
    targetPort: 80
    nodePort: 31000
  selector:
    app: vote

