replicaCount: 1

image:
  repository: dockersamples/examplevotingapp_vote
  pullPolicy: IfNotPresent
  tag: latest

service:
  type: NodePort
  port: 8080
  targetPort: 80
  nodePort: 31000

resources:
  requests:
    memory: "256Mi"
    cpu: "200m"
  limits:
    memory: "512Mi"
    cpu: "500m"

hpa:
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 20 
serviceAccount:
  create: true
