apiVersion: v1
kind: Service
metadata:
  labels:
    app: vote
  name: {{ .Release.Name }}  # Use release name for dynamic service name
spec:
  type: {{ .Values.vote.service.type | default "NodePort" }}  # Default to NodePort if not specified
  ports:
  - name: "vote-service"
    port: {{ .Values.vote.service.port }}  # Port the service will expose
    targetPort: 80  # This is the port on your container as defined in the deployment.yaml
    nodePort: {{ .Values.vote.service.nodePort }}  # NodePort for external access
  selector:
    app: vote
