apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: db
  name: db
spec:
  replicas: 3
  selector:
    matchLabels:
      app: db
  serviceName: "db"
  template:
    metadata:
      labels:
        app: db
    spec:
      nodeSelector:
        kubernetes.io/hostname: k8sworker1  # Ensure this matches the node where the PV is located
      containers:
        - image: postgres:15-alpine
          name: postgres
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: db-data
      volumeClaimTemplates:
        - metadata:
            name: db-data
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 10Gi
            storageClassName: local-storage
