apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: redis
  name: redis
spec:
  replicas: 3
  selector:
    matchLabels:
      app: redis
  serviceName: "redis"
  template:
    metadata:
      labels:
        app: redis
    spec:
      nodeSelector:
        kubernetes.io/hostname: k8sworker2  # Ensure this matches the node where the PV is located
      containers:
        - image: redis:alpine
          name: redis
          volumeMounts:
            - mountPath: /data
              name: redis-data
      volumeClaimTemplates:
        - metadata:
            name: redis-data
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 1Gi
            storageClassName: local-storage
