apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app: redis
spec:
  clusterIP: None  # Headless service to allow direct pod access via DNS
  selector:
    app: redis
  ports:
  - port: 6379
    targetPort: 6379
    name: redis
